=== weijian-meng/elan-lexicon-editor/lexicon/LexiconComponent-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    <!-- 
    <xs:import schemaLocation="http://www.w3.org/2001/xml.xsd" namespace="http://www.w3.org/XML/1998/namespace"/>
     -->
    <xs:element name="lexicon">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="header" type="header"/>
                <xs:element name="entry" type="entry" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <!-- schema or format version -->
            <xs:attribute name="schemaVersion" type="xs:string">
                <xs:annotation>
                    <xs:documentation>The version of the schema or format is also part of the schema location url/name.
                        Could enforce the value with, in this case, default="1.0".
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="producer" type="xs:string" use="optional"/>
        </xs:complexType>
        
        <xs:key name="entryKey">
            <xs:selector xpath="entry"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref refer="entryKey" name="entryKeyRef">
            <xs:selector xpath="entry"/>
            <xs:field xpath="@entryRef"/>
        </xs:keyref>
    </xs:element>
    
    <xs:complexType name="header">
        <!-- sub elements -->
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="language" type="xs:string">
                <xs:annotation>
                    <xs:documentation>For now one language is allowed, the main language this lexicon is about 
                        (this denotes the language of the lexical-unit, citation etc.). 
                        ISO 639-3 3 letter code is assumed but not enforced (the type is xs:string)</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="description" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>A free form textual description of and information on the lexicon.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="version" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>The version of the lexicon itself, not the format version.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <!-- not fully supported yet: custom field specifications, field configuration, preferred sort order -->
            <xs:element name="custom-fields" type="custom_field_specification" minOccurs="0"/>
            <xs:element name="field-configs" type="field_configuration" minOccurs="0"/>
            <xs:element name="sort-order" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <!--  entry type -->
    <xs:complexType name="entry">
        <xs:sequence>
            <xs:element name="lexical-unit" type="xs:string">
                <xs:annotation>
                    <xs:documentation>lexical-unit (LIFT terminology, a lexicon interchange format) instead of lemma / headword etc. 
                        Assumes language is the "main" language.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="citation" type="xs:string" minOccurs="0"/>
            <xs:element name="morph-type" type="xs:string" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>If not present, a default value is assumed. This element could/should be linked to a 
                        controlled vocabulary (or a "range" in lift).</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="variant" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Simple variant field, assumes the same morph-type and language as the lexical-unit</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="phonetic" type="phonetic" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Not fully supported yet.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="field" type="custom_field" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>Provides a way to add custom fields to the lexicon.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="sense" type="sense" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="dateCreated" type="xs:dateTime"/>
        <xs:attribute name="dateModified" type="xs:dateTime"/>
        <xs:attribute name="order" type="xs:int" use="optional">
            <xs:annotation>
                <xs:documentation>An attribute to explicitely set the order for entries with the same lexical-unit (e.g. homonyms).</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="entryRef" type="xs:IDREF">
            <xs:annotation>
                <xs:documentation>A reference to a "parent" unit. Fields are "inherited" unless redefined.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    
    <!-- entry level (sub)elements -->  
    <!-- sense type -->
    <xs:complexType name="sense">
        <xs:sequence>
            <xs:element name="grammatical-category" type="xs:string">
                <xs:annotation>
                    <xs:documentation>Grammatical category or part of speech (in LIFT part of "grammatical-info").
                    This element should/could be linked to a controlled vocabulary or "range".</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="gloss" type="gloss" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="definition" type="definition" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="example" type="example" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="comment" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="internal-note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="field" type="custom_field" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="order" type="xs:int" use="required">
            <xs:annotation><xs:documentation>The sense number.</xs:documentation></xs:annotation>
        </xs:attribute>
    </xs:complexType>
    
    <!-- sense level (sub)elements -->
    <!-- gloss and definition extend the complex type "text_lang". JAXB creates separate classes that extend the TextLang class -->
    <xs:complexType name="gloss">
        <xs:annotation><xs:documentation>Glosses can be specified in multiple languages.</xs:documentation></xs:annotation>
        <xs:simpleContent>
            <xs:extension base="text_lang"/>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="definition">
        <xs:annotation><xs:documentation>Definitions can be specfied in multiple languages.</xs:documentation></xs:annotation>
        <xs:simpleContent>
            <xs:extension base="text_lang"/>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="phonetic">
        <xs:annotation><xs:documentation>Phonetic representations can be specfied in multiple languages or systems.</xs:documentation></xs:annotation>
        <xs:simpleContent>
            <xs:extension base="text_lang"/>
        </xs:simpleContent>
    </xs:complexType>
   
    <xs:complexType name="text_lang">
        <xs:annotation><xs:documentation>A type consisting of a string value and a language attribute.</xs:documentation></xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attributeGroup ref="language"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="example">
        <xs:annotation>
            <xs:documentation>An example element (not fully implemented yet).</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <!-- text and translation are of the same "text plus language" complex type  -->
            <xs:element name="text" type="text_lang"/>
            <xs:element name="translation" type="text_lang" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="source-ref" type="xs:string" minOccurs="0">
                <xs:annotation><xs:documentation>A literature reference or similar</xs:documentation></xs:annotation>
            </xs:element>
            <xs:element name="fragment-ref" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>A reference to an annotation or (fragment of) a media file.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!-- common attribute -->
    <xs:attributeGroup name="language">
        <xs:annotation>
            <xs:documentation>
                This is currently of type string (free form).
                Alternatives could be a 3 letter code, or xs:language, or a language-id reference (as in EAF).
            </xs:documentation>
        </xs:annotation>
        <!-- --><xs:attribute name="lang" type="xs:string" use="optional"/>
        <!-- <xs:attribute ref="xml:lang"/>  -->
    </xs:attributeGroup>
    
    <!-- any 3 letter code? Not used. -->
    <xs:simpleType name="three_letter_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]{3}"/> 
        </xs:restriction>
    </xs:simpleType>
    
    <!-- a basic custom field on the level of entry and sense -->
    <xs:complexType name="custom_field">
        <xs:annotation>
            <xs:documentation>
               For adding user defined fields to lexical entries. Not supported yet.
               The type of the name of the fields is at the moment defined as xs:NCName so that
               in a conversion it can be used as an XML element name. 
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attributeGroup ref="language"/>
                <xs:attribute name="name" type="xs:NCName" use="required"/>
                <!-- maybe support an attribute like this, so that custom fields can be linked to multimedia fragments? -->
                <xs:attribute name="mediaRef" type="xs:anyURI"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <!-- header elements of complex type, not fully implemented yet -->
    <xs:complexType name="custom_field_specification">
        <xs:annotation>
            <xs:documentation>Specification of custom fields.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="field-spec" type="custom_field_spec" minOccurs="0" maxOccurs="unbounded"/>           
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="custom_field_spec">
        <xs:annotation>
            <xs:documentation>A specification for a single custom field.</xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" type="xs:NCName" use="required">
                    <xs:annotation>
                        <xs:documentation>The name of the field. 
                            (The type is NCName so that in a conversion it can become an xml element.)</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="level" use="optional">
                    <xs:annotation>
                        <xs:documentation>Determines on what level(s) this field can occur.</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="entry"/>
                            <xs:enumeration value="sense"/>
                            <xs:enumeration value="all"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:complexType name="field_configuration">
        <xs:annotation>
            <xs:documentation>Configuration of fields.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="field-config" type="field_config" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="field_config">
        <xs:annotation>
            <xs:documentation>Configuration of a single field.</xs:documentation>
        </xs:annotation>
        <xs:attribute name="fieldName" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>The name of one of the standard or custom fields.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="displayName" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>The preferred display label for the field (a hint for user interfaces).</xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="rangeRef" type="xs:string" use="optional"><!-- cv-ref ? -->
            <xs:annotation>
                <xs:documentation>A reference to the identifier or name of a controlled vocabulary or range.
                    It is still to be decided where the ranges are stored and how to link to the definitions.</xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== weijian-meng/elan-lexicon-editor/lexicon/lexicon-template.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lexicon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1.0" producer="ELAN Lexicon Component" xsi:schemaLocation="http://www.mpi.nl/tools/elan/LexiconComponent-1.0.xsd">
    <header>
        <name>Gurung lexicon</name>
        <language>Gurung</language>
        <version>0.1.0</version>
        <custom-fields>
            <field-spec name="Loan_from" level="entry"></field-spec>
        </custom-fields>
    </header>
    <entry id="e_8e52ef8b-485d-4085-b838-bbd350d5bb5d" dateCreated="2025-03-05T16:02:38.386Z" dateModified="2025-03-05T16:15:55.299Z" order="1">
        <lexical-unit>-mari</lexical-unit>
        <citation>-mari</citation>
        <morph-type>suffix</morph-type>
        <variant>-mora</variant>
        <variant>-mara</variant>
        <sense id="s_85f3d867-0ff0-4b00-869a-92b99e462f2d" order="1">
            <grammatical-category>tam</grammatical-category>
            <gloss>CV.SEQ</gloss>
            <gloss lang="nep">-era</gloss>
        </sense>
    </entry>
    <entry id="e_d25519fd-3e67-44c4-92a9-a09b7f813a48" dateCreated="2025-03-05T14:53:22.323Z" dateModified="2025-03-05T14:53:46.523Z" order="1">
        <lexical-unit>-r</lexical-unit>
        <morph-type>suffix</morph-type>
        <sense id="s_7eb1f420-e242-4a30-9d9a-3d83d8fbe825" order="1">
            <grammatical-category>case</grammatical-category>
            <gloss>LOC</gloss>
        </sense>
    </entry>
    <entry id="e_030661fe-307f-4b50-bde3-821dafa36753" dateCreated="2025-03-05T16:04:01.739Z" dateModified="2025-03-05T16:14:29.135Z" order="1">
        <lexical-unit>-ũ</lexical-unit>
        <citation>-ũ</citation>
        <morph-type>suffix</morph-type>
        <variant>-m</variant>
        <sense id="s_26cbf48e-af42-488d-9be8-132d87314dbc" order="1">
            <grammatical-category>tam</grammatical-category>
            <gloss>NPST</gloss>
        </sense>
    </entry>
    <entry id="e_f86e93d1-2bda-4edc-84d9-ab1c2165e1c5" dateCreated="2025-03-05T15:10:33.410Z" dateModified="2025-03-05T15:10:44.575Z" order="1">
        <lexical-unit>bhina</lexical-unit>
        <morph-type>stem</morph-type>
        <sense id="s_3e960a68-2f93-41bd-8a7f-89edc3661fac" order="1">
            <grammatical-category>n</grammatical-category>
            <gloss>rooster</gloss>
        </sense>
    </entry>
    <entry id="e_683f7952-f40e-4144-8350-f461af15137d" dateCreated="2025-03-05T15:09:04.134Z" dateModified="2025-03-05T16:13:33.255Z" order="1">
        <lexical-unit>mausom</lexical-unit>
        <morph-type>stem</morph-type>
        <phonetic></phonetic>
        <field name="Loan_from">nep</field>
        <sense id="s_e2101892-b4c1-4cbc-897e-c3cce938afc4" order="1">
            <grammatical-category>n</grammatical-category>
            <gloss>weather</gloss>
        </sense>
    </entry>
    <entry id="e_18ab2bed-a0ba-4abe-ad4b-c295321b58d4" dateCreated="2025-03-05T16:10:50.770Z" dateModified="2025-03-05T16:13:45.313Z" order="1">
        <lexical-unit>video</lexical-unit>
        <morph-type>stem</morph-type>
        <field name="Loan_from">eng</field>
        <sense id="s_d7c77b04-3fb1-482d-b87c-8171ddb37cee" order="1">
            <grammatical-category>n</grammatical-category>
            <gloss>video</gloss>
        </sense>
    </entry>
</lexicon>

=== weijian-meng/elan-lexicon-editor/lexicon/sample-lexicon copy.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lexicon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaVersion="1.0" producer="ELAN Lexicon Component" xsi:schemaLocation="http://www.mpi.nl/tools/elan/LexiconComponent-1.0.xsd">
  <header>
    <name>Gurung lexicon</name>
    <language>Gurung</language>
    <version>0.1.0</version>
    <custom-fields>
      <field-spec name="Loan_from" level="entry"/>
      <field-spec name="example" level="sense"/>
    </custom-fields>
    <description>sample lexicon for testing</description>
    <sort-order>a b c d e f g</sort-order>
  </header>
  <entry id="e_8e52ef8b-485d-4085-b838-bbd350d5bb5d" dateCreated="2025-03-05T16:02:38.386Z" dateModified="2025-03-05T16:15:55.299Z" order="1">
    <lexical-unit>-mari</lexical-unit>
    <citation>-mari</citation>
    <morph-type>suffix</morph-type>
    <variant>-mora</variant>
    <variant>-mara</variant>
    <sense id="s_85f3d867-0ff0-4b00-869a-92b99e462f2d" order="1">
      <grammatical-category>tam</grammatical-category>
      <gloss>CV.SEQ</gloss>
      <gloss lang="nep">-era</gloss>
    </sense>
  </entry>
  <entry id="e_d25519fd-3e67-44c4-92a9-a09b7f813a48" dateCreated="2025-03-05T14:53:22.323Z" dateModified="2025-03-05T14:53:46.523Z" order="1">
    <lexical-unit>-r</lexical-unit>
    <morph-type>suffix</morph-type>
    <sense id="s_7eb1f420-e242-4a30-9d9a-3d83d8fbe825" order="1">
      <grammatical-category>case</grammatical-category>
      <gloss>LOC</gloss>
    </sense>
  </entry>
  <entry id="e_030661fe-307f-4b50-bde3-821dafa36753" dateCreated="2025-03-05T16:04:01.739Z" dateModified="2025-03-05T16:14:29.135Z" order="1">
    <lexical-unit>-ũ</lexical-unit>
    <citation>-ũ</citation>
    <morph-type>suffix</morph-type>
    <variant>-m</variant>
    <sense id="s_26cbf48e-af42-488d-9be8-132d87314dbc" order="1">
      <grammatical-category>tam</grammatical-category>
      <gloss>NPST</gloss>
    </sense>
  </entry>
  <entry id="e_f86e93d1-2bda-4edc-84d9-ab1c2165e1c5" dateCreated="2025-03-05T15:10:33.410Z" dateModified="2025-03-05T15:10:44.575Z" order="1">
    <lexical-unit>bhina</lexical-unit>
    <morph-type>stem</morph-type>
    <sense id="s_3e960a68-2f93-41bd-8a7f-89edc3661fac" order="1">
      <grammatical-category>n</grammatical-category>
      <gloss>rooster</gloss>
    </sense>
  </entry>
  <entry id="e_da4d2cb4-084a-488c-8204-477959ddf19c" dateCreated="2025-03-05T15:26:37.178Z" dateModified="2025-03-05T15:26:50.137Z" order="1">
    <lexical-unit>khale</lexical-unit>
    <morph-type>stem</morph-type>
    <sense id="s_06821dfe-ff52-42c7-8d65-c914c11d42b1" order="1">
      <grammatical-category>conj</grammatical-category>
      <gloss>because.of</gloss>
    </sense>
  </entry>
  <entry id="e_0371d01f-15ec-497a-ad0f-54f6732276e4" dateCreated="2025-03-05T14:52:45.258Z" dateModified="2025-03-05T14:53:18.137Z" order="1">
    <lexical-unit>kri</lexical-unit>
    <morph-type>stem</morph-type>
    <sense id="s_80af3bbe-2b22-4eaa-b599-73570c5fc523" order="1">
      <grammatical-category>num</grammatical-category>
      <gloss>one</gloss>
    </sense>
  </entry>
  <entry id="e_683f7952-f40e-4144-8350-f461af15137d" dateCreated="2025-03-05T15:09:04.134Z" dateModified="2025-03-05T16:13:33.255Z" order="1">
    <lexical-unit>mausom</lexical-unit>
    <morph-type>stem</morph-type>
    <phonetic/>
    <field name="Loan_from">nep</field>
    <sense id="s_e2101892-b4c1-4cbc-897e-c3cce938afc4" order="1">
      <grammatical-category>n</grammatical-category>
      <gloss>weather</gloss>
    </sense>
  </entry>
  <entry id="e_18ab2bed-a0ba-4abe-ad4b-c295321b58d4" dateCreated="2025-03-05T16:10:50.770Z" dateModified="2025-03-05T16:13:45.313Z" order="1">
    <lexical-unit>video</lexical-unit>
    <morph-type>stem</morph-type>
    <field name="Loan_from">eng</field>
    <sense id="s_d7c77b04-3fb1-482d-b87c-8171ddb37cee" order="1">
      <grammatical-category>n</grammatical-category>
      <gloss>video</gloss>
    </sense>
  </entry>
  <entry id="e_bad765ac-bab9-4563-a6b0-6d22ae44204e" dateCreated="2025-03-24T17:51:08.136Z" dateModified="2025-03-24T17:52:01.046Z">
    <lexical-unit>mra</lexical-unit>
    <morph-type>stem</morph-type>
    <sense id="s_ff1608e1-f001-4909-9a2d-0d756fea6845" order="1">
      <grammatical-category>n</grammatical-category>
      <gloss>door</gloss>
    </sense>
    <sense id="s_76a26b29-a8e5-4772-b27e-6c116a1b5e0e" order="2">
      <grammatical-category>v</grammatical-category>
      <gloss>dig.hole</gloss>
    </sense>
  </entry>
</lexicon>

=== weijian-meng/elan-lexicon-editor/lexicon/test-py-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lexicon schemaVersion="1.0" producer="ELAN Lexicon Editor" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mpi.nl/tools/elan/LexiconComponent-1.0.xsd">
	<header>
		<name>test</name>
		<language>en</language>
		<description/>
		<version>1.0</version>
		<custom-fields/>
	</header>
	<entry id="e_63b26fa2-9850-4ba2-be0a-336f4d6537d6" dateCreated="2025-09-12T21:48:42.925Z" dateModified="2025-09-14T20:48:08.168Z">
		<lexical-unit>apples</lexical-unit>
		<morph-type>stem</morph-type>
		<sense id="s_2cc3bb05-1c13-407e-9770-f6c5cd77ca5b" order="1">
			<grammatical-category>n</grammatical-category>
			<gloss>apple</gloss>
		</sense>
	</entry>
	<entry id="e_a3dc82ed-05e5-4e16-bb1a-87bb03fd906f" dateCreated="2025-09-14T20:48:10.467Z" dateModified="2025-09-14T21:16:06.739Z">
		<lexical-unit>pears</lexical-unit>
		<morph-type>stem</morph-type>
		<sense id="s_d923a0cc-0883-48b5-b76d-681210706956" order="1">
			<grammatical-category>n</grammatical-category>
			<gloss>pear</gloss>
		</sense>
	</entry>
	<entry id="e_7074a2ad-d5c2-4c53-aae3-d940d4504e71" dateCreated="2025-09-15T16:29:19.622Z" dateModified="2025-09-15T16:30:14.499Z">
		<lexical-unit>peachy</lexical-unit>
		<morph-type>stem</morph-type>
		<sense id="s_8acd574b-13f8-4c92-9084-cae28ce67bd3" order="1">
			<grammatical-category>n</grammatical-category>
			<gloss>peach</gloss>
		</sense>
	</entry>
</lexicon>

=== weijian-meng/elan-lexicon-editor/lexicon/Untitled.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lexicon producer="ELAN Lexicon Editor" schemaVersion="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mpi.nl/tools/elan/LexiconComponent-1.0.xsd"><entry dateCreated="2025-12-10T15:54:27.988Z" dateModified="2025-12-10T16:38:30.941Z" id="e_aea08ce8-2393-44d1-90a7-e4bf7debc567"><lexical-unit>something?!#%((</lexical-unit><morph-type>stem-what</morph-type><sense id="s_49bb854d-91e8-4028-a69d-b503c9ee3b4f" order="1"><gloss>whatever</gloss><grammatical-category>v</grammatical-category></sense><sense id="s_3321668d-6fe6-4715-9e8c-50c2db94e245" order="2"><gloss>Something</gloss><grammatical-category>n</grammatical-category></sense></entry><header><custom-fields/><date-created>2025-12-10T15:53:55.726Z</date-created><language>en</language><lexicon-name>New Lexicon</lexicon-name><name>something</name></header></lexicon>
